### ISSUE TITLE
add support for YAML config files in core.Tool

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#1047]
Right now `Tools` (and `Components`) are configured via `traitlets.config`, which is nice , but so far only supports JSON config files out of the box (see e.g. the code in lst-chain that uses this already).  It would be nice, and probably quite easy, to add support for YAML config files.  

Internally, traitlets.config just turns the config file into a dict(), and presumably this is done with a call to `json.loads()` somewhere.  It should be straightforward to make it also use `yaml.loads()` if the config file is YAML-based. Probably we can implement this in our Tool class directly, rather than asking for traitlets to support it. Tool is already a sub-class of `traitlets.config.Application`. 

## example:
Current config file (for PedestalCalculator):
```json
{
   "version": 1,

   "PedestalHDF5Writer": {
     "calculator_product": "PedestalIntegrator",
     "output_file":"pedestal.hdf5",
     "log_level":"DEBUG"
   },         
   "EventSource": {
      "input_url": "/ctadata/franca/LST/LST-1.1.Run00168.0000.fits.fz",
      "max_events": 100
   },
   "PedestalCalculator":{
     "sample_size": 90,
     "sample_duration":1000,
     "tel_id":0,
      "charge_product":"LocalPeakIntegrator"
   },
    "LocalPeakIntegrator":{
     "window_shift": 4,
     "window_width":10
    }
}
```

could become this (which is more human-friendly):
```yaml
version: 1
EventSource:
  input_url: /ctadata/franca/LST/LST-1.1.Run00168.0000.fits.fz
  max_events: 100
LocalPeakIntegrator:
  window_shift: 4
  window_width: 10
PedestalCalculator:
  charge_product: LocalPeakIntegrator
  sample_duration: 1000
  sample_size: 90
  tel_id: 0
PedestalHDF5Writer:
  calculator_product: PedestalIntegrator
  log_level: DEBUG
  output_file: pedestal.hdf5
```
