### ISSUE TITLE
where to store MC DL1 information in event structure

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#1493]
I'm starting to refactor stage1.py such that the writing is separate from the calculations (creating a DL1Writer Component), and I've noticed that so far we have nearly everything needed in the event structure *except* the `MCDL1CameraContainer`, which is created on-the-fly inside the script, but is never written to the "event".  Now that I'm separating the computation from the writing, everything written must be in the event, so the question is: where would be a good place to put this info?

## Current status:

We have 2 containers for DL1 camera info. 

### Real DL1 images and parameters
**In Event Structure**:  `event.dl1.tel[X]`
**Written to**: */dl1/event/telescope/{images,parameters}/tel_X* in the output
```
ctapipe.containers.DL1CameraContainer:
                         image: Numpy array of camera image, after waveform
                                extraction.Shape: (n_pixel) as a 1-D array with
                                type float32
                     peak_time: Numpy array containing position of the peak of
                                the pulse as determined by the extractor. Shape:
                                (n_pixel) as a 1-D array with type float32
                    image_mask: Boolean numpy array where True means the pixel
                                has passed cleaning. Shape: (n_pixel) as a 1-D
                                array with type bool
                  parameters.*: Parameters derived from images
```

### Simulated DL1 images and parameters
For simulated info we have a similar class:
**In Event Structure**: nowhere
**Written to**: */dl1/simulation/telescope/{images,parameters}/tel_X* in the output
```
ctapipe.containers.MCDL1CameraContainer:
             true_image: Numpy array of camera image in PE as simulated
                                before noise has been added. Shape: (n_pixel) as
                                a 1-D array with type float32
             true_parameters.*: Parameters derived from the true_image
```
 
### Other Simulated info
**In Event Structure**: `event.mc.tel[x]`:
**Written to**: nowhere in the output
```
ctapipe.containers.MCCameraEventContainer:
                    true_image: Numpy array of camera image in PE as simulated
                                before noise has been added. Shape: (n_pixel)
                      dc_to_pe: DC/PE calibration arrays from MC file
                      pedestal: pedestal calibration arrays from MC file
                   azimuth_raw: Raw azimuth angle [radians from N->E] for the
                                telescope
                  altitude_raw: Raw altitude angle [radians] for the telescope
                   azimuth_cor: the tracking Azimuth corrected for pointing
                                errors for the telescope
                  altitude_cor: the tracking Altitude corrected for pointing
                                errors for the telescope
```

## Options

1. get rid of `MCCameraEventContainer` and replace it with `MCDL1CameraContainer`: are any of the other fields still used? I think the pointing already goes in `event.pointing`, and `dc_to_pe` and `pedestal` are not really per-event quantities and are already in `event.calibration.tel[x].dl1` (`DL1CameraCalibrationContainer`). 

2. put MCDL1CameraContainer somewhere in `event.dl1.tel[x]` (a bit ugly, since this is only there for simulations)

Any others?
