### ISSUE TITLE
Wrongly removed (or added?) true_ prefix in simulated impact containers with ctapipe-process

### ISSUE THREAD

**Issue by nbiederbeck** [cta-observatory/ctapipe#1972]
**Describe the bug**
Running `ctapipe-process` from DL1 to DL1 removes `true_` prefix of simulated impact container.

Or is it that the simteleventsource appends a `true_` prefix? All the other containers (e.g. simulation/event/telescope/parameters) don't have this prefix at all.

**To Reproduce**
1. `ctapipe-process -i simtel -o dl1` 
2. `ctapipe-process -i dl1 -o dl1_again`

**Expected behavior**
Fields should not be renamed by ctapipe-process.

**Supporting information**
If applicable, add screenshots, logs, or a traceback to help illustrate the bug.

**Additional context**
![ctapipe](https://user-images.githubusercontent.com/15156697/176372996-1b11c1e6-36df-4854-a404-cb889cf66896.png)

config:
```yml
DataWriter:
  transform_image: True
  transform_peak_time: True
  write_images: True
  write_parameters: True
  write_showers: True
```
