### ISSUE TITLE
Change API of `Reconstructor` and `ShowerProcessor` to allow multiple reconstructions and common predictions

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#2071]
**Please describe the use case that requires this feature.**

Currently, the `ctapipe.reco.Reconstructor` baseclass has the API `__call__(self, event: ArrayEvent) -> ReconstructedGeoemtryContainer`.

This is inflexible, as it makes it impossible to have reconstruction algorithms that directly predict a combination of geometry, energy and particle type, like ImPACT, machine learning, etc.

Also, `ShowerProcessor` only allows a single algorithm.

**Describe the solution you'd like**

Change the API of the general base `Reconstructor` to be `__call__(self, event) -> None`, filling any dl2 container it generates into the event structure.

Change `ShowerReconstructor` to allow a list of `Reconstructor` base classes that are **executed in order**.

I.e. the config should look like this:

```
ProcessorTool:
    ShowerProcessor:
        reconstructors: 
            - HillasReconstructor
            - HillasIntersection
            - EnergyRegressor
            - ImPACT
            - ParticleIDClassifier
        ParticleIDClassifier:
             model_path: ...
        ImPACT:
             template_path:  
             geometry_seed: HillasReconstructor
             energy_seed: RandomForestRegressor 
```

This would still (due to how traitlets works) have the limitation of not being able to e.g. use different configurations of the same reconstructor but would be a big step forward

**Describe alternatives you've considered**

**Additional context**

This means that also the classes in the new ml branch should then be subclasses of `Reconstructor`
