### ISSUE TITLE
Quality query falling back to default for ctapipe-optimize-event-selection

### ISSUE THREAD

**Issue by BastienLacave** [cta-observatory/ctapipe#2699]
when running `ctapipe-optimize-event-selection` I have the following error:

`2025-02-13 09:33:06,171 ERROR [ctapipe.ctapipe-optimize-event-selection] (tool.run): Caught unexpected exception: Error evaluating expression '('multiplicity 4', 'np.count_nonzero(HillasReconstructor_telescopes,axis=1) >= 4')': name 'HillasReconstructor_telescopes' is not defined
Traceback (most recent call last):
  File "/home/blacave/CTLearn/Software/ctapipe/src/ctapipe/core/tool.py", line 439, in run
    self.start()
  File "/home/blacave/CTLearn/Software/ctapipe/src/ctapipe/tools/optimize_event_selection.py", line 150, in start
    events, count, meta = loader.load_preselected_events(
  File "/home/blacave/CTLearn/Software/ctapipe/src/ctapipe/irf/preprocessing.py", line 227, in load_preselected_events
    selected = events[self.epp.quality_query.get_table_mask(events)]
  File "/home/blacave/CTLearn/Software/ctapipe/src/ctapipe/core/qualityquery.py", line 138, in get_table_mask
    for i, res in enumerate(self.engine(table), start=1):
  File "/home/blacave/CTLearn/Software/ctapipe/src/ctapipe/core/expression_engine.py", line 44, in __call__
    raise ExpressionError(
ctapipe.core.expression_engine.ExpressionError: Error evaluating expression '('multiplicity 4', 'np.count_nonzero(HillasReconstructor_telescopes,axis=1) >= 4')': name 'HillasReconstructor_telescopes' is not defined`

But in my config I specify

```
EventPreProcessor:
  energy_reconstructor: "CTLearn"
  gammaness_classifier: "CTLearn"
  geometry_reconstructor: "CTLearn"
  quality_criteria:
    - ["multiplicity", "np.count_nonzero(CTLearn_telescopes,axis=1) == 2"]
    - ["valid classifier", "CTLearn_is_valid"]
    - ["valid geom reco", "CTLearn_is_valid"]
    - ["valid energy reco", "CTLearn_is_valid"]`
```

[public-conf.txt](https://github.com/user-attachments/files/18780788/public-conf.txt)

**Comment by Hckjs** [comment]
Hey Bastien,
I think you need to set the quality_criteria trait of the `EventQualityQuery` Component to make the config system work because its not a direct trait of the `EventPreProcessor` Component, e.g.:
```
EventPreProcessor: 
    energy_reconstructor: "CTLearn" 
    gammaness_classifier: "CTLearn" 
    geometry_reconstructor: "CTLearn"

    EventQualityQuery:
        quality_criteria: 
            - ["multiplicity", "np.count_nonzero(CTLearn_telescopes,axis=1) == 2"] 
            - ["valid classifier", "CTLearn_is_valid"]
            - ["valid geom reco", "CTLearn_is_valid"] 
            - ["valid energy reco", "CTLearn_is_valid"]
```
Just like in [this example](https://github.com/cta-observatory/ctapipe/blob/main/src/ctapipe/resources/optimize_cuts.yaml)
